### ISSUE TITLE
I can get the DMA part to work, but anyone got any idea about the POI?

### ISSUE THREAD

**Issue by IcedDoggie** [uark-cviu/Micron-BERT#15]
I welcome any idea of brainstorming or any calls if needed.

![image](https://github.com/uark-cviu/Micron-BERT/assets/4167312/2c4be751-9ed6-4ca4-a977-b44f46e53742)

**Comment by IcedDoggie** [comment]
![img31](https://github.com/uark-cviu/Micron-BERT/assets/4167312/004c7a94-5596-47f5-8d55-b69182191141)

**Comment by IcedDoggie** [comment]
![image](https://github.com/uark-cviu/Micron-BERT/assets/4167312/1a9e7e44-8022-4ad4-8f67-8eb9bb469834)
This is the closest i could get so far. Any thoughts?

**Comment by Atlantic4Li** [comment]
Do you have the pre-trained Micron-BERT model? Can you give me a download link if so?

**Comment by IcedDoggie** [comment]
@Atlantic4Li https://unioulu-my.sharepoint.com/:u:/g/personal/hkhor19_univ_yo_oulu_fi/ESMDey8S6phAjhltyiGDdO0BUB0FvAYDDJvej6NdrEp3EA?e=vdHIMQ

**Comment by Atlantic4Li** [comment]
> @Atlantic4Li https://unioulu-my.sharepoint.com/:u:/g/personal/hkhor19_univ_yo_oulu_fi/ESMDey8S6phAjhltyiGDdO0BUB0FvAYDDJvej6NdrEp3EA?e=vdHIMQ

Thank you very much

**Comment by chenmiao11** [comment]
can you tell me how to get this figure?

**Comment by IcedDoggie** [comment]
@chenmiao11 i used the pretrained weights, then need to make sure to use the correct class token, then also need to specifically change the normal attention to cross attention

**Comment by IcedDoggie** [comment]
https://github.com/IcedDoggie/Micron-bert-poor-replication the code is here

**Comment by caoendian** [comment]
> [@chenmiao11](https://github.com/chenmiao11) i used the pretrained weights, then need to make sure to use the correct class token, then also need to specifically change the normal attention to cross attention
The pretrained model download link is expired. Can you provide a pre-trained model

**Comment by caoendian** [comment]
@IcedDoggie The pretrained model download link is expired. Can you provide a pre-trained model
