### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by kalpa61** [uark-cviu/Micron-BERT#17]
hi, thanks for your work. If I want to train on the CASME II dataset, which images of the dataset should I use? Each sample has a series of images from OnsetFrame to OffsetFrame. For each sample, Should I keep only OnsetFrame, ApexFrame, OffsetFrame images? I'm confused

**Comment by Prism-hua** [comment]
Hello@kalpa61, have you solved this problem? It would be helpful if you could share your solution with me. Thanks a lot!

**Comment by kalpa61** [comment]
@Prism-hua 你好，有不同的处理方式，可以用一系列输入，也可以使用单独的帧输入，不过微表情这个领域的开源工作比较少，我目前还在尝试

**Comment by lzl2040** [comment]
@kalpa61 您好，请问可以分享一下相关微表情数据集吗，SMIC、CASME II、CASME III等，它们申请好麻烦
